### ISSUE TITLE
ポスターなど整備したら消えた

### ISSUE THREAD

**Issue by fuchinosuke** [team-morumotto/GameOfTagMansion_V3#27]
confrict回避のため泣く泣く削除したため現在別シーンを作って作り直し中

**Comment by waya0125** [comment]
[`41a707d`](https://github.com/team-morumotto/GameOfTagMansion_V3/commit/41a707d60d40502006a6c5681a3c6dff028028e5) にてコミットは修正（正確には作り直し）されました。
